## Numpy Practical Implementation.

In [1]:
import numpy as np
print(np.__version__)


2.3.1


### What is numpy?

##### Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

### What is Array?

##### In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a[0]

np.int64(1)

Array is Mutable?----yes

In [4]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

Array have slice notation

In [5]:
a[:3]

array([10,  2,  3])

In [6]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

Two- and higher-dimensional arrays can be initialized from nested Python sequences:

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a[1,3]

np.int64(8)

Array Attributes

This section covers the ndim, shape, size, and dtype attributes of an array.

The number of dimensions of an array is contained in the ndim attribute.

In [9]:
a.ndim

2

In [10]:
a.shape
len(a.shape) == a.ndim

True

In [11]:
a.size
import math
a.size == math.prod(a.shape)

True

In [12]:
a.dtype

dtype('int64')

How to create a basic Array.

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.ones(2)

array([1., 1.])

### Create an Empty array with 2 elements.

In [16]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

### Range of elements.

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [19]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(5, 100, num=5)

array([  5.  ,  28.75,  52.5 ,  76.25, 100.  ])

Specifying your data type

In [21]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

Adding, removing, and sorting elements
This section covers np.sort(), np.concatenate()

Sorting an array is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

If you start with this array:

In [22]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [23]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [25]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [27]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

How do you know the shape and size of an array?
This section covers ndarray.ndim, ndarray.size, ndarray.shape

In [28]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [29]:
array_example.ndim

3

In [30]:
array_example.size

24

In [31]:
array_example.shape

(3, 2, 4)

matlab 3 block hai, har block me 2 row hai , aur har row me 4 element hai.

----
Can you reshape an array?
This section covers arr.reshape()

Yes!

In [32]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [33]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

---
### How to convert a 1D array into a 2D array (how to add a new axis to an array)
This section covers np.newaxis, np.expand_dims

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

For example, if you start with this array:

In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [36]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [37]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [38]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [39]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [40]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [41]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

---
Indexing and Slicing

In [42]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [44]:
print(a[a < 5])

[1 2 3 4]


In [45]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [46]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [47]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [48]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


You can also use np.nonzero() to select elements or indices from an array.

Starting with this array:

In [49]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [50]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [51]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [52]:
print(a[b])

[1 2 3 4]


---
How to create an array from existing data
This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [53]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [55]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [56]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [57]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [58]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [60]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

---
Basic Operation
:>>>This section covers addition, subtraction, multiplication, division, and more

In [61]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [62]:
data - ones
data * data
data / data

array([1., 1.])

In [64]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [65]:
b = np.array([[1, 1], [2, 2]])

In [66]:
b.sum(axis=0)

array([3, 3])

In [67]:
b.sum(axis=1)

array([2, 4])

---
Broadcasting:>>> There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [68]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [69]:
data.max()
data.min()
data.sum()

np.float64(3.0)

In [70]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [71]:
a.sum()

np.float64(4.8595784)

In [72]:
a.min()

np.float64(0.05093587)

In [74]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

---
Creating Matrices

You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [75]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [76]:
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [77]:
data.max()
data.min()
data.sum()

np.int64(21)

In [79]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)


array([5, 6])

In [80]:
data.max(axis=1)

array([2, 5, 6])

In [81]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [82]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [83]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [84]:
np.ones((3, 2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [85]:
np.zeros((3, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [88]:
rng = np.random.default_rng()
rng.random((3, 2)) 

array([[0.45509514, 0.05635772],
       [0.20936617, 0.57786155],
       [0.50535592, 0.13243104]])

---
### Generating Random Numbers

In [89]:
rng.integers(5, size=(2, 4)) 

array([[4, 1, 1, 3],
       [1, 2, 1, 1]])

---
How to get unique items and counts

In [90]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [91]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [92]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


2D Array:

In [93]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [94]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [95]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [96]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


---
Transposing and reshaping a matrix
This section covers arr.reshape(), arr.transpose(), arr.T

In [97]:
data.reshape(2, 3)
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [100]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

---
How to reverse an array
This section covers np.flip()

In [101]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
reversed_arr = np.flip(arr)

In [103]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


Reversing a 2D array

A 2D array works much the same way.

If you start with this array:

In [104]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [105]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [106]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [107]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [108]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


---
Reshaping and flattening multidimensional arrays
This section covers .flatten(), ravel()



In [109]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [110]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [112]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


# Thanks